# Generated by Django 6.0.6 on 2026-07-08 17:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import users.models.base_user
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number in international format, e.g. +491701234567.', regex='^\\+?[1-9]\\d{7,14}$')], verbose_name='phone number')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='avatar')),
                ('is_owner', models.BooleanField(default=False, help_text='Grants access to landlord (property owner) features.', verbose_name='owner status')),
                ('is_agent', models.BooleanField(default=False, help_text='Grants access to real estate agent features.', verbose_name='agent status')),
                ('is_support', models.BooleanField(default=False, help_text='Grants access to support ticket features. Settable only via admin, never via a public serializer.', verbose_name='support status')),
                ('is_moderator', models.BooleanField(default=False, help_text='Grants access to listing moderation features. Settable only via admin, never via a public serializer.', verbose_name='moderator status')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other / Non-binary'), ('unspecified', 'Prefer not to say')], default='unspecified', max_length=20, verbose_name='gender')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', users.models.base_user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='agent_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(max_length=255, verbose_name='company name')),
                ('license_number', models.CharField(max_length=64, verbose_name='license number')),
                ('is_certified', models.BooleanField(default=False, verbose_name='certified status')),
                ('website', models.URLField(blank=True, null=True, verbose_name='website')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='bio / specialization')),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled by User'), ('banned', 'Banned by Admin')], default='active', max_length=20, verbose_name='status')),
            ],
            options={
                'verbose_name': 'agent profile',
                'verbose_name_plural': 'agent profiles',
            },
        ),
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='owner_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tax_id', models.CharField(help_text='Used for tax reporting (Germany) / legal entities.', max_length=32, verbose_name='tax ID / INN')),
                ('bio', models.TextField(blank=True, help_text="Public description shown on the owner's listing page.", verbose_name='bio')),
                ('is_company', models.BooleanField(default=False, help_text='Whether the owner is a legal entity rather than a private individual.', verbose_name='is company')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='company name')),
                ('registration_number', models.CharField(blank=True, help_text='Commercial register number (Handelsregisternummer), if applicable.', max_length=64, verbose_name='registration number')),
                ('languages', models.CharField(blank=True, help_text='Comma-separated list of languages spoken by the owner, e.g. German, English.', max_length=255, verbose_name='languages')),
                ('is_verified', models.BooleanField(default=False, help_text="Whether a moderator has verified the owner's documents.", verbose_name='verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('verification_document', models.FileField(blank=True, null=True, upload_to='verification/owners/', verbose_name='verification document')),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled by User'), ('banned', 'Banned by Admin')], default='active', max_length=20, verbose_name='status')),
            ],
            options={
                'verbose_name': 'owner profile',
                'verbose_name_plural': 'owner profiles',
            },
        ),
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tenant_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('passport_data', models.CharField(help_text='Sensitive identity document data; store encrypted or masked.', max_length=255, verbose_name='passport data')),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled by User'), ('banned', 'Banned by Admin')], default='active', max_length=20, verbose_name='status')),
            ],
            options={
                'verbose_name': 'tenant profile',
                'verbose_name_plural': 'tenant profiles',
            },
        ),
    ]
