# Generated by Django 6.0.6 on 2026-07-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='agentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'disabled', 'banned'])), name='agent_profile_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='ownerprofile',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'disabled', 'banned'])), name='owner_profile_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='tenantprofile',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'disabled', 'banned'])), name='tenant_profile_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('gender__in', ['male', 'female', 'other', 'unspecified'])), name='user_gender_valid'),
        ),
    ]
