# Generated by Django 6.0.6 on 2026-07-10 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_agentprofile_agent_profile_status_valid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
