# Generated by Django 6.0.6 on 2026-07-11 17:11

import importlib

from django.db import migrations, models

# Migration module names start with a digit, so they can't be reached via a normal `from x import
# y` statement - importlib is the standard workaround.
agent_cert_trigger_module = importlib.import_module("listings.migrations.0006_property_agent_cert_trigger")


def drop_dependent_triggers(apps, schema_editor):
    """
    SQLite has no in-place ALTER for tables with an explicit Meta.constraints list (User has
    ``user_gender_valid``) - it rebuilds the table via CREATE new + INSERT ... SELECT + DROP old.
    Because listings_property.owner_id is a FK to users_user, Django's schema editor cascades that
    rebuild to listings_property too, and the plain INSERT it runs to repopulate it fires
    ``property_agent_cert_check_insert`` (a BEFORE INSERT trigger, see listings/migrations/
    0006_property_agent_cert_trigger.py) mid-rebuild, when users_user doesn't exist under its
    normal name yet - producing "no such table: main.users_user". Dropping the trigger before the
    rebuild and recreating it after (below) sidesteps this without touching the trigger's logic.
    MySQL's ALTER TABLE ADD COLUMN never rebuilds dependent tables, so this is SQLite-only.
    """
    if schema_editor.connection.vendor == "sqlite":
        agent_cert_trigger_module.drop_triggers(apps, schema_editor)


def recreate_dependent_triggers(apps, schema_editor):
    if schema_editor.connection.vendor == "sqlite":
        agent_cert_trigger_module.create_triggers(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_agent_decertify_guard_trigger'),
        ('listings', '0006_property_agent_cert_trigger'),
    ]

    operations = [
        migrations.RunPython(drop_dependent_triggers, reverse_code=recreate_dependent_triggers),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Set once the user confirms their email via the verification link. Informational only for now.', verbose_name='email verified'),
        ),
        migrations.RunPython(recreate_dependent_triggers, reverse_code=drop_dependent_triggers),
    ]
