# Generated by Django 6.0.6 on 2026-07-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='viewed at')),
            ],
            options={
                'verbose_name': 'property view',
                'verbose_name_plural': 'property views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(max_length=255, verbose_name='search query')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'search history entry',
                'verbose_name_plural': 'search history',
                'ordering': ['-created_at'],
            },
        ),
    ]
