# Generated by Django 6.0.6 on 2026-07-08 17:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='street')),
                ('house_number', models.CharField(max_length=20, verbose_name='house number')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'amenity',
                'verbose_name_plural': 'amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('text', 'Text (OpenAI Moderation API)'), ('image', 'Image (AWS Rekognition)'), ('manual', 'Manual review')], max_length=20, verbose_name='source')),
                ('decision', models.CharField(choices=[('clean', 'Clean'), ('flagged', 'Flagged'), ('error', 'Check failed')], max_length=20, verbose_name='decision')),
                ('reason', models.TextField(blank=True, help_text='Human-readable summary of flagged categories.', verbose_name='reason')),
                ('raw_response', models.JSONField(blank=True, help_text='Raw API response, kept for audit purposes.', null=True, verbose_name='raw response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'moderation log',
                'verbose_name_plural': 'moderation logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='postal code')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('state', models.CharField(help_text='German federal state (Bundesland), e.g. Berlin, Bayern.', max_length=100, verbose_name='state')),
            ],
            options={
                'verbose_name': 'postal code',
                'verbose_name_plural': 'postal codes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('rent_type', models.CharField(choices=[('daily', 'Daily'), ('long_term', 'Long-term')], max_length=20, verbose_name='rent type')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='price per day')),
                ('rooms_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='rooms count')),
                ('is_active', models.BooleanField(default=True, help_text='Toggled by the owner to show/hide the listing from search results.', verbose_name='is active')),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text="Result of automated + human review of this listing's text and photos.", max_length=20, verbose_name='moderation status')),
                ('listed_as', models.CharField(choices=[('owner', 'As owner (own property)'), ('agent', 'As agent (on behalf of a client)')], default='owner', help_text="Whether the owner is listing their own property, or an agent acting on a client's behalf.", max_length=20, verbose_name='listed as')),
                ('power_of_attorney_document', models.FileField(blank=True, help_text='Required when listed_as=AGENT; proves authorization to list this specific property.', null=True, upload_to='listings/power_of_attorney/', verbose_name='power of attorney document')),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='image')),
            ],
            options={
                'verbose_name': 'property image',
                'verbose_name_plural': 'property images',
            },
        ),
    ]
