# Generated by Django 6.0.6 on 2026-07-08 18:20

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='property',
            name='property_price_per_day_positive',
        ),
        migrations.AddField(
            model_name='property',
            name='price_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required for LONG_TERM listings (German long-term rent is always quoted monthly, e.g. Kaltmiete). Price in EUR.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='price per month (EUR)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required for DAILY listings. Price in EUR - this platform only serves the German market.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='price per day (EUR)'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('price_per_day__isnull', True), ('price_per_day__gt', 0), _connector='OR'), name='property_price_per_day_positive'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('price_per_month__isnull', True), ('price_per_month__gt', 0), _connector='OR'), name='property_price_per_month_positive'),
        ),
    ]
