# Generated by Django 6.0.6 on 2026-07-10 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_property_property_price_per_day_positive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='moderationlog',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['text', 'image', 'manual'])), name='moderationlog_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='moderationlog',
            constraint=models.CheckConstraint(condition=models.Q(('decision__in', ['clean', 'flagged', 'error'])), name='moderationlog_decision_valid'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('rent_type__in', ['daily', 'long_term'])), name='property_rent_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('moderation_status__in', ['pending', 'approved', 'rejected'])), name='property_moderation_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('listed_as__in', ['owner', 'agent'])), name='property_listed_as_valid'),
        ),
    ]
