# Generated by Django 6.0.6 on 2026-07-10 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_moderationlog_moderationlog_source_valid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('price_per_day__isnull', False), ('rent_type', 'daily')), models.Q(('price_per_month__isnull', False), ('rent_type', 'long_term')), _connector='OR'), name='property_price_required_for_rent_type'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('listed_as', 'owner'), models.Q(('listed_as', 'agent'), ('power_of_attorney_document__isnull', False), models.Q(('power_of_attorney_document', ''), _negated=True)), _connector='OR'), name='property_poa_required_for_agent'),
        ),
    ]
