# Generated by Django 6.0.6 on 2026-07-12 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_property_image_limit_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.PositiveIntegerField(verbose_name='property id')),
                ('property_title', models.CharField(max_length=255, verbose_name='property title')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='deleted at')),
                ('deleted_by', models.ForeignKey(help_text="The listing's owner - only the owner may delete their own listing.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_deletions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'property deletion log',
                'verbose_name_plural': 'property deletion logs',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
