# Generated by Django 6.0.6 on 2026-07-13 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_propertydeletionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='postalcode',
            name='city',
            field=models.CharField(db_index=True, max_length=100, verbose_name='city'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_active', 'moderation_status'], name='property_visible_idx'),
        ),
    ]
