# Generated by Django 6.0.6 on 2026-07-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_postalcode_city_property_property_visible_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='is_flagged',
            field=models.BooleanField(default=False, verbose_name='flagged'),
        ),
    ]
