# Generated by Django 6.0.6 on 2026-07-20 16:38

import importlib

from django.db import migrations, models

_trigger_migration = importlib.import_module(
    "listings.migrations.0007_property_image_limit_trigger"
)


def recreate_trigger(apps, schema_editor):
    """
    On SQLite, the AddField below rebuilds the table from scratch (SQLite can't add a NOT
    NULL column with a dropped default in place), which silently drops the trigger from
    migration 0007 - SQLite triggers belong to the table they're defined on. MySQL's plain
    ALTER TABLE ADD COLUMN never touches the trigger, so drop-then-recreate is a harmless
    no-op there.
    """
    _trigger_migration.drop_trigger(apps, schema_editor)
    _trigger_migration.create_trigger(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_postalcode_city_property_property_visible_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='is_flagged',
            field=models.BooleanField(default=False, verbose_name='flagged'),
        ),
        migrations.RunPython(
            recreate_trigger, reverse_code=_trigger_migration.drop_trigger
        ),
    ]
