"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import sys
from datetime import timedelta
from pathlib import Path

from celery.schedules import crontab
from environ import Env
from django.utils.translation import gettext_lazy as _


BASE_DIR = Path(__file__).resolve().parent.parent
env = Env()
# manage.py test runs with DEBUG=True (via .env.test) so SECURE_SSL_REDIRECT below stays off -
# the test client talks plain http and would otherwise get a 301 instead of the real response.
env_file = ".env.test" if "test" in sys.argv else ".env"
env.read_env(BASE_DIR / env_file)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

# ALLOWED_HOSTS = env.str('ALLOWED_HOSTS').split(',')
ALLOWED_HOSTS = env.str("ALLOWED_HOSTS", default="127.0.0.1,localhost").split(",")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "django_filters",
    "users.apps.UsersConfig",
    "listings.apps.ListingsConfig",
    "bookings.apps.BookingsConfig",
    "reviews.apps.ReviewsConfig",
    "notifications.apps.NotificationsConfig",
    "support.apps.SupportConfig",
    "analytics.apps.AnalyticsConfig",
    "drf_spectacular",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if env.bool("USE_REMOTE", default=False):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": env.str("DB_NAME"),
            "USER": env.str("DB_USER"),
            "PASSWORD": env.str("DB_PASSWORD"),
            "HOST": env.str("DB_HOST"),
            "PORT": env.int("DB_PORT"),
        },
    }


else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

LANGUAGES = [
    ("en", _("English")),
    ("de", _("German")),
]

LOCALE_PATHS = [BASE_DIR / "locale"]

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# CACHE CONFIGURATION

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env.str("REDIS_URL", default="redis://127.0.0.1:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}


AUTH_USER_MODEL = "users.User"

# Allowed file extensions for property images
PROPERTY_IMAGE_ALLOWED_EXTENSIONS = ["jpg", "jpeg", "png", "gif", "webp"]
MAX_PROPERTY_IMAGES = 10

# Retention window for cleanup_analytics (GDPR storage-limitation, no legal hold like Booking/Ticket).
ANALYTICS_RETENTION_DAYS = env.int("ANALYTICS_RETENTION_DAYS", default=90)


# CONTENT MODERATION (listings app)

AWS_ACCESS_KEY_ID = env.str("AWS_ACCESS_KEY_ID", default="")
AWS_SECRET_ACCESS_KEY = env.str("AWS_SECRET_ACCESS_KEY", default="")
AWS_REGION_NAME = env.str("AWS_REGION_NAME", default="eu-central-1")

OPENAI_API_KEY = env.str("OPENAI_API_KEY", default="")

# Shared credentials for seed_data's Faker-generated test users (DEBUG-only command).
SEED_PASSWORD = env.str("SEED_PASSWORD", default="TestPass123!")
SEED_EMAIL_DOMAIN = env.str("SEED_EMAIL_DOMAIN", default="example.com")

# Sent synchronously (unlike the Celery-backed booking notification in bookings/tasks.py); console backend by default.
EMAIL_BACKEND = env.str(
    "EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend"
)
EMAIL_HOST = env.str("EMAIL_HOST", default="")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_HOST_USER = env.str("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env.str("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
DEFAULT_FROM_EMAIL = env.str(
    "DEFAULT_FROM_EMAIL", default="noreply@django-rental-service.local"
)

# Frontend base URL for password-reset/verification links in emails; placeholder until a frontend exists.
FRONTEND_URL = env.str("FRONTEND_URL", default="http://localhost:3000")

# Reuses FRONTEND_URL as the trusted origin; CORS_EXTRA_ORIGINS covers any additional ones.
CORS_ALLOWED_ORIGINS = [FRONTEND_URL] + [
    origin for origin in env.str("CORS_EXTRA_ORIGINS", default="").split(",") if origin
]
CORS_ALLOW_CREDENTIALS = True

# Separate Redis DB index from CACHES so a cache flushdb doesn't wipe queued tasks.
CELERY_BROKER_URL = env.str("CELERY_BROKER_URL", default="redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = env.str(
    "CELERY_RESULT_BACKEND", default="redis://127.0.0.1:6379/0"
)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TASK_ALWAYS_EAGER = env.bool("CELERY_TASK_ALWAYS_EAGER", default=False)

# Runs via `celery -A config beat` alongside the worker (survives container restarts, unlike an OS cron entry).
CELERY_BEAT_SCHEDULE = {
    "cleanup-analytics-daily": {
        "task": "analytics.tasks.cleanup_analytics_task",
        "schedule": crontab(hour=3, minute=0),
    },
}

# Uncaught exceptions and logger.exception() calls go to errors.log in addition to the console.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "errors_file": {
            "level": "ERROR",
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "errors.log",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console", "errors_file"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console", "errors_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# DJANGO REST FRAMEWORK

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_FILTER_BACKENDS": ("django_filters.rest_framework.DjangoFilterBackend",),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.AnonRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "user": "1000/day",
        "anon": "100/day",
        "register": "10/hour",
        "password_reset": "5/hour",
        "email_verification": "5/hour",
    },
    "EXCEPTION_HANDLER": "common.exceptions.exception_handler",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}


SPECTACULAR_SETTINGS = {
    "TITLE": "Django Rental Service API",
    "DESCRIPTION": "API for managing rental properties, bookings, and user accounts.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # Strips the '/v1' prefix so drf-spectacular groups tags by resource instead of one flat "v1" section.
    "SCHEMA_PATH_PREFIX": r"/api/v1",
    # Booking/Ticket/profile "status" fields share a name but different TextChoices - disambiguate the enum names.
    "ENUM_NAME_OVERRIDES": {
        "BookingStatusEnum": "bookings.models.status.BookingStatusChoices",
        "TicketStatusEnum": "support.models.ticket.Ticket.StatusChoices",
        "ProfileStatusEnum": "common.models.choices.ProfileStatusChoices",
    },
    # Only the docs pages are public; each endpoint still enforces its own permissions regardless.
    "SERVE_PERMISSIONS": ["rest_framework.permissions.AllowAny"],
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "displayRequestDuration": True,
        "filter": True,
        "showExtensions": True,
        "persistAuthorization": True,
    },
}

# Guarded by `not DEBUG` so local runserver over plain http:// isn't broken by SSL/HSTS redirects.
if not DEBUG:
    # nginx terminates TLS and proxies to gunicorn over plain HTTP; without this, Django can't
    # tell the original request was HTTPS and SECURE_SSL_REDIRECT loops forever.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = (
        31536000  # 1 year, the standard HSTS preload-eligible minimum.
    )
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
