# Generated by Django 6.0.6 on 2026-07-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('status', models.CharField(choices=[('pending', 'Pending owner approval'), ('booked', 'Booked'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', help_text="Set to BOOKED/CANCELLED only by the property's owner or agent approving or declining the request.", max_length=20, verbose_name='status')),
                ('price_frozen', models.DecimalField(decimal_places=2, editable=False, help_text="Copy of Property.price_per_day at booking creation time; later owner price changes don't affect this contract.", max_digits=10, verbose_name='price frozen')),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
