# Generated by Django 6.0.6 on 2026-07-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='price_frozen',
            field=models.DecimalField(decimal_places=2, editable=False, help_text="Copy of Property.price_per_day (DAILY) or Property.price_per_month (LONG_TERM) at booking creation time; later owner price changes don't affect this contract.", max_digits=10, verbose_name='price frozen'),
        ),
    ]
