# Generated by Django 6.0.6 on 2026-07-10 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_price_frozen'),
        ('listings', '0004_moderationlog_moderationlog_source_valid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'booked', 'paid', 'cancelled'])), name='booking_status_valid'),
        ),
    ]
